shellEmulator: true

# unusable due to flawed strategy that results in false positives: https://github.com/orgs/pnpm/discussions/11084#discussioncomment-16355455
# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: off

allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
